name: Julia CI (Build & Test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - name: Install dependencies
        # Notice we tell GitHub to run this INSIDE the subfolder
        working-directory: ./OpticalWavePropSim
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

      - name: Run Master Simulation Smoke Test
        working-directory: ./OpticalWavePropSim
        env:
          GKSwstype: "100"
        run: |
          julia --project=@. -e '
            using OpticalWavePropSim
            # We must adjust these paths to go back up and into examples
            include("../examples/Chapter9/example_pt_source_atmos_setup.jl");
            include("../examples/Chapter9/analysis_pt_source_atmos_samp.jl");
            include("../examples/Chapter9/example_pt_source_vac_prop.jl");
            include("../examples/Chapter9/example_pt_source_turb_prop.jl");
          '
